[env]
TERM = "alacritty"

[font]
size = 12.0

[font.normal]
family = "Fira Code"

[window]
decorations = "none"
opacity = 0.95
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 160
lines = 40

[window.padding]
x = 10
y = 10

[general]
import = ["/home/antonio/.config/alacritty/themes/nord_modified.toml"]
live_config_reload = true
